DataDog/omnibus-ruby

lib/omnibus/build_version.rb

Compliant with dd-agent stable/nightly builds

New build-version output method

---

lib/omnibus/build_version.rb
lib/omnibus/packagers/deb.rb
lib/omnibus/packagers/rpm.rb

The colon is not really HTTP compliant and also, this has been done to have consistent rpm names regarding the previous versions.

[rpm] Remove epoch from final RPM name

---

lib/omnibus/packagers/deb.rb
lib/omnibus/packagers/rpm.rb
resources/rpm/spec.erb

This replaces the dirty hack that was there before and actually makes
things work for real with RPM packages as explained below.
The epoch shouldn't be included as part of the version string for RPMs
but as a separate field in the package metadata (contrary to what's
happening for debs). I updated our fork by actually (re)adding an epoch
DSL for RPM and DEB builds which is definitely cleaner than what we were
doing before. Will make a PR for that against `chef/omnibus` when I get
the chance, it might definitely be a relevant DSL to other Omnibus users.

Add a real epoch DSL for RPM and DEB builds

---

lib/omnibus/packagers/rpm.rb
resources/rpm/spec.erb

The build was broken because only `:` was inserted into the RPM package
name when no epoch was set which wasn't caught by the `\d+:` RegEx. No
when no epoch is set, no epoch is passed to the `rpmbuild` command and
the RPM doesn't have any extra colon. When it is defined, the epoch is
removed by the regex as it was before :)

Fixed the RPM build when the epoch DSL is unset

---

lib/omnibus/build_version.rb

iWe now (almost) stick to Omnibus way of versinong our package relying
on git tags... except for one thing: we're still escaping the '+' symbol
into a '.' for compliance with Amazon S3.
Here's a build that worked https://circleci.com/gh/DataDog/docker-dd-agent-build-deb-i386/449 .

Finally get rid of dd_agent_format

---

lib/omnibus/file_syncer.rb

Allows us to preserve the modified time of `.py` files, thus the
corresponding `.pyc` files which are generated before the sync
stay valid.

Preserve file properties when syncing files

---

lib/omnibus/packagers/rpm.rb

Do not list `filesystem` directories in the package because some
packages installed by default on Amazon Linux EMR images have a complete
disregard for the permissions defined by their own `filesystem` pkg,
and then conflict with the datadog-agent pkg.
Example: `service-nanny` on Amazon Linux EMR 4.3.0:
```
$ rpm -lqv service-nanny | grep /usr/bin$
drwxr-xr-x    2 root    root                        0 Nov 25 02:16 /usr/bin
$ rpm -lqv filesystem | grep /usr/bin$
dr-xr-xr-x    2 root    root                        0 Jan  6  2012 /usr/bin
```
(notice the different permissions...)
So for EMR images  it's impossible to follow the RPM packaging
guidelines and list the directories owned by `filesystem` with the
correct permissions.
As an aside, we need to test the agent packaging on Amazon Linux …

Fix RPM package for amazon linux EMR

---

lib/omnibus/packagers/deb.rb
lib/omnibus/packagers/rpm.rb
lib/omnibus/project.rb

A package extension can be sumarized as running
`apt-get install package`
`build project`
`apt-get remove package`
`package project`
This means the project will require the package to be installed
to properly behave. Also, the project's package won't contain
any dependency already shipped with the extended package, thus
will be lighter
NB: leaving windows and osx untouched for now

[SDK] Support package extension

---

lib/omnibus/fetchers/net_fetcher.rb

There's an intermittent nil error that occurs on fetching sometimes, this fix was applied upstream to solve it (https://github.com/chef/omnibus/pull/691), and it will solve it here as well. The error trace is below:
```
====/usr/lib64/ruby/gems/2.1.0/bundler/gems/omnibus-ruby-4f2d154c2ed0/lib/omnibus/fetchers/net_fetcher.rb:180:in `each': comparison of NilClass with 13843 failed (ArgumentError)
from /usr/lib64/ruby/gems/2.1.0/bundler/gems/omnibus-ruby-4f2d154c2ed0/lib/omnibus/fetchers/net_fetcher.rb:180:in `min'
from /usr/lib64/ruby/gems/2.1.0/bundler/gems/omnibus-ruby-4f2d154c2ed0/lib/omnibus/fetchers/net_fetcher.rb:180:in `block in download'
from /usr/lib64/ruby/2.1.0/open-uri.rb:331:in `call'
from /usr/lib64/ruby/2.1.0/open-uri.rb:331:in `block (3 levels) in open_http'
from …
```

fixes intermittent nil error on downloads

---

lib/omnibus/packager.rb

SUSE requires an RPM, adding this to the hash will allow omnibus to correctly determine what it needs to build.

adds suse to packager

---

lib/omnibus/fetchers/net_fetcher.rb

If the files are owned by a high user ID (typically > 65536) then on
some environments (for instance in docker containers running on
CircleCI) the extraction fails.
Example of such an error:
```
<filename>: Cannot change ownership to uid <high_UID>, gid 5000: Invalid argument
```
To fix this, don't preserve file ownership when extracting tars by
using the `o` option of tar. Reference on this option: [GNU tar man page](https://www.gnu.org/software/tar/manual/html_section/tar_22.html#g_t_002d_002dno_002dsame_002downer)

[net_fetcher] Don't preserve ownership of files when extracting tars

---

lib/omnibus/build_version.rb

`+` is not allowed in S3 object names so make sure that there's no
remaining `+` in the version string.
This fixes Agent6 deploys.

[dd_agent_format] Replace all `+` from version string with `.`

---

lib/omnibus/build_version_dsl.rb

Now that we replace all `+` with `.` in version strings (since #27),
we need to update the logic that detects timestamps in version strings
accordingly, otherwise we'll add a `+timestamp` suffix to the version
strings.

[version] Fix timestamp detection in version

---

lib/omnibus/builder.rb

As it's a build dep and not a runtime one.

[config_guess] link it from /tmp/build

---

lib/omnibus/project.rb

package extension is broken because it now allows multiple packagers.
Package extension is used in the integration sdk to include the various files that we use in the agent, but it's broken because there are multiple packagers now allowed. However, all of the omnibus only have one packager at the moment.

fixes package extension

---

lib/omnibus/packagers/msi.rb

Omnibus has facility for signing the outer package (msi or exe).  However, the included (installed) exes aren't signed and should be.

Add code to sign included exes.  Don't do DLLs for now

---

lib/omnibus/fetchers/git_fetcher.rb

As they're needed for the versioning.

[git_fetcher] always fetch tags

---

lib/omnibus/packagers/msi.rb
lib/omnibus/packagers/windows_base.rb

Bundle signing wasn't implemented properly.  The  bundle engine needs to be extracted and signed separately, otherwise the package is invalid and is treated as if it has a bad signature.

[Windows] Fix bundle signing

---

lib/omnibus/fetchers/git_fetcher.rb
lib/omnibus/software.rb

Using this option ensures that whatever version of git is used, we
consistently pull the tags in all cases (even when the latest local
commit is up-to-date with the remote but doesn't have a remote tag).
When the option is set, we fetch tags in a separate git command
because until git v1.9 `git fetch` was not a strict subset of
`git fetch --tags` (see http://stackoverflow.com/a/20608181 for more
details). When we get rid of older versions of git, we'll be able
to only use `git fetch --tags`.

[git_fetcher] Add option to always fetch tags from remote

---

lib/omnibus/packagers/rpm.rb

SLES uses zypper but extensions were only set up to use yum. This will enable zypper as well

allow zypper to be used to install a package in package extension

---

lib/omnibus/packagers/rpm.rb

This is very ugly, however it's necessary. The install does not work, since the docker image does not have some of the files we depend upon for the datadog agent to work. It installs, it just fails when it tries to start. So, we have to do an `|| true`. It's really ugly, but there's no other solution for now.

Gets suse install to work

---

lib/omnibus/fetchers/net_fetcher.rb

specification as an indication that the argument is off-box.
There are multiple different tar executables available (that we install).  Which one you execute depends on how the path is set up.  This change accounts for tar that requires `--force-local` to handle windows paths (with ":" in them), and the tar that doesn't.
Required to make both the agent6 and agent5 build process complete independent of which TAR is used, and what order binaries are added to the path (the current agent5 build process works as is, but could break if the paths are changed, etc.)

[windows] add "force-local" so that tar won't view the ":" in the drive

---

lib/omnibus/packagers/msi.rb

a specific directory looking for the extra confs; make it take an
optional configuration option.

[Windows] Make the <msi> packager a bit more generic. Was hard coded to

---

lib/omnibus/packagers/msi.rb
lib/omnibus/packagers/windows_base.rb

hardcoded to the bin and dist directories.
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

Add a generic list of files to sign; implementation is currently

---

lib/omnibus/packagers/msi.rb

Previous checkin allowed package to specify list of files to be signed.  However, caused an error if the package didn't specify a list.  This PR fixes that; allows the list to be empty
--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

Allow signfiles list to be empty

---

lib/omnibus/packagers/msi.rb

ours) being signed by us.
Was signing all EXEs in installdir/bin and installdir/dist.  This was missing some files, and resulted in signing some files that were redistributed (shouldn't be signed).  Remove the wildcard altogether, and just sign the explicit list of files.

[windows] remove wildcard signing.  Was resulting in some binaries (not

---

omnibus.gemspec

Pin license_scout to `1.0.1` like the omnibus fellas do. 
`license_scout ~> 2.02` pulls in rugged which requires `cmake` for building which we do not have available in our builders.

[license_scout] pin to 1.x

---

Gemfile
omnibus.gemspec

`pedump` patched fork is now dead, moving back to upstream gem.
Also some gemfile cleanup.
--------------------------------------------------
/cc @chef/omnibus-maintainers <- This ensures the Omnibus Maintainers team are notified to review this PR.

[pedump] dropping dead fork using upstream + gemfile cleanup

---

lib/omnibus/cli.rb
lib/omnibus/config.rb
lib/omnibus/fetchers/net_fetcher.rb
lib/omnibus/s3_cache.rb
lib/omnibus/s3_helpers.rb
omnibus.gemspec

First, this backports changes from 5.6 that allow better connection to s3 endpoints and allows you to fill the bucket cache prior to running the build.
Second, this allows you to download from s3 buckets that aren't public.
Third, it expands the number of options allowed for credentials, including instance profiles and role authentication.

Better S3 Caching
